# Generated by Django 3.0.3 on 2020-03-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('landmark', models.CharField(max_length=256)),
                ('area', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('pin_code', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10)),
                ('timing', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
